"""Small fix

Revision ID: bfea8751e94c
Revises: b1b45e152a97
Create Date: 2024-04-14 22:17:11.767128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfea8751e94c'
down_revision: Union[str, None] = 'b1b45e152a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nodes', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
